# Generated by Django 4.2.11 on 2024-05-04 10:34

import common.methods
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("contact_details", models.TextField()),
                ("address", models.TextField()),
                ("on_time_delivery_rate", models.FloatField(default=0.0)),
                ("quality_rating_avg", models.FloatField(default=0.0)),
                ("average_response_time", models.FloatField(default=0.0)),
                ("fulfillment_rate", models.FloatField(default=0.0)),
                (
                    "vendor_code",
                    models.CharField(
                        default=common.methods.get_unique_code_chars,
                        editable=False,
                        max_length=16,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "vendor",
                "verbose_name_plural": "vendors",
            },
        ),
        migrations.CreateModel(
            name="HistoricalPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("history_date", models.DateTimeField(auto_now_add=True)),
                ("on_time_delivery_rate", models.FloatField()),
                ("quality_rating_avg", models.FloatField()),
                ("average_response_time", models.FloatField()),
                ("fulfillment_rate", models.FloatField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendors.vendor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Historical Performance",
                "verbose_name_plural": "Historical Performances",
                "ordering": ["-history_date"],
            },
        ),
    ]
