name: Django Test Suite with Coverage

on:
  push:
    branches:
      - '*'  # This triggers the workflow on every branch

jobs:
  test:
    name: Run Django Tests with Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage report
        run: |
          cd src  # Navigate to the directory containing manage.py
          coverage run manage.py test -v 2 && coverage report
